# Generated by Django 4.2.7 on 2024-07-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='image',
            new_name='Location_Image',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='name',
            new_name='Location_Name',
        ),
    ]
