# Generated by Django 5.0.3 on 2024-07-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_rename_image_locations_location_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turf_Name', models.CharField(max_length=30)),
                ('Turf_Image', models.ImageField(default='null.jpg', upload_to='images')),
                ('Turf_Booking_price', models.IntegerField()),
                ('Turf_Facilities', models.CharField(max_length=60)),
                ('Turf_Location', models.CharField(max_length=30)),
                ('Turf_Manager_Name', models.CharField(max_length=30)),
                ('Turf_Working_time', models.CharField(max_length=30)),
            ],
        ),
    ]
