# Generated by Django 5.0.3 on 2024-07-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManagerReg_Name', models.CharField(max_length=30)),
                ('ManagerReg_Image', models.ImageField(default='Null.jpg', upload_to='images')),
                ('ManagerReg_Email', models.EmailField(max_length=254)),
                ('ManagerReg_PhNumber', models.IntegerField()),
                ('ManagerReg_Password', models.CharField(max_length=12)),
                ('ManagerReg_Experience', models.CharField(max_length=40)),
                ('ManagerReg_Gender', models.CharField(max_length=15)),
                ('ManagerReg_Status', models.IntegerField(default=0)),
            ],
        ),
    ]
