# Generated by Django 4.2.7 on 2024-09-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0002_alter_manager_managerreg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='ManagerReg_Assigned',
            field=models.TextField(default='NotAssigned'),
        ),
    ]
