# Generated by Django 4.2.7 on 2024-09-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0003_manager_managerreg_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='ManagerReg_Assigned',
        ),
    ]
