# Generated by Django 4.2.7 on 2024-07-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserReg_Name', models.CharField(max_length=30)),
                ('UserReg_Email', models.EmailField(max_length=254)),
                ('UserReg_PhNumber', models.IntegerField()),
                ('UserReg_Password', models.CharField(max_length=30)),
            ],
        ),
    ]
