# Generated by Django 5.0.3 on 2024-07-28 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_turfs'),
        ('UserApp', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_Date', models.DateField()),
                ('Booking_Time', models.CharField(max_length=40)),
                ('Booking_Turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.turfs')),
                ('Booking_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.uregister')),
            ],
        ),
    ]
