# Generated by Django 5.0.3 on 2024-07-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booking_Status',
            field=models.TextField(default='Pending'),
        ),
    ]
